# Human-readable name
name: 'Reacticon 4'


# Description and purpose
description: 'Reacticon presentation bundle'


# Build path
output: '../../../public/js/react'


# Konstan output folder path
konstanOutput: '../../../public/js'


# Service Worker output folder path
serviceWorkerOutput: '../../../public'


# Public URL
url: '/static/build'
